src/Entity/Motion.php
<?php

namespace App\Entity;

use App\Entity\Translation\TranslatableTrait;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MotionRepository")
 *
 * @method MotionTranslation translate($locale = null, $fallbackToDefault = true)
 * @ORM\Table(name="motion")
 */
class Motion
{
    use TranslatableTrait;
    const PAGINATION_LIST_LIMIT = 8;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToMany(targetEntity="Tag", inversedBy="motions", cascade={"persist"})
     */
    private $tags;

    /**
     * @ORM\OneToMany(targetEntity="Acquisition", mappedBy="motion", cascade={"persist"})
     */
    private $acquisitions;


    /**
     * Constructor.
     */
    public function __construct()
    {
        $this->tags = new ArrayCollection();
        $this->acquisitions = new ArrayCollection();
    }

    /**
     * Get id.
     *
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    public function getTitle()
    {
        return $this->proxyCurrentLocaleTranslation('getTitle');
    }

    public function setTitle($title)
    {
        $this->proxyCurrentLocaleTranslation('setTitle', [$title]);
        $this->mergeNewTranslations();
    }

    /**
     * @param Tag[] $tags
     *
     * @return $this
     */
    public function setTags(array $tags): Motion
    {
        foreach ($tags as $tag) {
            $this->addTag($tag);
        }

        return $this;
    }

    /**
     * Add tag.
     *
     * @param Tag $tag
     *
     * @return Motion
     */
    public function addTag(Tag $tag): Motion
    {
        $this->tags[] = $tag;

        return $this;
    }

    /**
     * Remove tag.
     *
     * @param Tag $tag
     */
    public function removeTag(Tag $tag)
    {
        $this->tags->removeElement($tag);
    }

    /**
     * Get tags.
     *
     * @return Collection
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * Add acquisition.
     *
     * @param Acquisition $acquisition
     *
     * @return Motion
     */
    public function addAcquisition(Acquisition $acquisition): Motion
    {
        $this->acquisitions[] = $acquisition;
        $acquisition->setMotion($this);

        return $this;
    }

    /**
     * Remove acquisition.
     *
     * @param Acquisition $acquisition
     */
    public function removeAcquisition(Acquisition $acquisition)
    {
        $this->acquisitions->removeElement($acquisition);
    }

    /**
     * Get acquisitions.
     *
     * @return Collection
     */
    public function getAcquisitions()
    {
        return $this->acquisitions;
    }

    /**
     * @return string
     */
    public function __toString()
    {
        return $this->getTitle();
    }
}

src/Entity/Respondent.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RespondentRepository")
 */
class Respondent
{
    const GENDERS = ['Male', 'Female'];
    const MIN_AGE = 1;
    const MAX_AGE = 120;

    const MOTOR_EXPERTISE_LEVELS = ['Beginner', 'Intermediate', 'Expert'];

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var int
     * @ORM\Column(type="smallint")
     */
    private $age;

    /**
     * @var string
     * @ORM\Column(type="string")
     */
    private $gender;

    /**
     * @var string
     * @ORM\Column(type="string", nullable=true)
     * @Assert\Length(min=3)
     */
    private $sensoryMotorExpertise;

    /**
     * @var string
     * @ORM\Column(type="string", nullable=true)
     * @Assert\Choice(choices=Respondent::MOTOR_EXPERTISE_LEVELS)
     */
    private $motorExpertiseLevel;

    /**
     * @var Recognition[]|ArrayCollection
     * @ORM\OneToMany(targetEntity="Recognition", mappedBy="respondent")
     */
    private $recognitions;

    public function __construct()
    {
        $this->recognitions = new ArrayCollection();
    }

    /**
     * @return mixed
     */
    public function getAge()
    {
        return $this->age;
    }

    /**
     * @param int $age
     *
     * @return $this
     */
    public function setAge(int $age)
    {
        $this->age = $age;

        return $this;
    }

    /**
     * @return string
     */
    public function getGender()
    {
        return $this->gender;
    }

    /**
     * @param mixed $gender
     *
     * @return $this
     */
    public function setGender($gender)
    {
        $this->gender = $gender;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return Recognition[]|ArrayCollection
     */
    public function getRecognitions()
    {
        return $this->recognitions;
    }

    /**
     * @param Recognition $recognition
     */
    public function addRecognition(Recognition $recognition)
    {
        $this->recognitions->add($recognition);
    }

    /**
     * @param Recognition $recognition
     */
    public function removeRecognition(Recognition $recognition)
    {
        $this->recognitions->removeElement($recognition);
    }

    /**
     * @return string
     */
    public function getSensoryMotorExpertise(): ?string
    {
        return $this->sensoryMotorExpertise;
    }

    /**
     * @param string $sensoryMotorExpertise
     */
    public function setSensoryMotorExpertise(?string $sensoryMotorExpertise)
    {
        $this->sensoryMotorExpertise = $sensoryMotorExpertise;
    }

    /**
     * @return string
     */
    public function getMotorExpertiseLevel(): ?string
    {
        return $this->motorExpertiseLevel;
    }

    /**
     * @param string $motorExpertiseLevel
     */
    public function setMotorExpertiseLevel(?string $motorExpertiseLevel)
    {
        $this->motorExpertiseLevel = $motorExpertiseLevel;
    }

    public function getRecognitionRate()
    {
        $allRates = 0;
        foreach ($this->recognitions as $recognition) {
            $allRates += $recognition->getRecognitionRate();
        }

        return ($this->recognitions->count()) ? $allRates / $this->recognitions->count() : 0;
    }
}

src/Controller/MotionController.php
<?php

namespace App\Controller;

use App\Entity\Motion;
use App\Form\MotionFilterType;
use App\Manager\PageManager;
use App\Manager\ParameterManager;
use App\Model\MotionFilter;
use App\Repository\MotionRepository;
use App\Service\Paginator;
use Pagerfanta\Pagerfanta;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Entity;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;

class MotionController extends AbstractController
{
    /**
     * @Route("/motions", defaults={"page": "1"}, name="motion_index")
     * @Route("/motions/{page}", requirements={"page": "[1-9]\d*"}, name="motion_index_paginated")
     * @Method({"GET","POST"})
     *
     * @param                  $page
     * @param Request          $request
     * @param MotionFilter     $motionFilter
     * @param MotionRepository $motionRepository
     * @param Paginator        $paginator
     * @param SessionInterface $session
     * @param PageManager      $pageManager
     * @param ParameterManager $parameterManager
     *
     * @return Response
     *
     * @internal param EntityManagerInterface $em
     * @internal param MotionRepository $motionRepository
     * @internal param EntityManagerInterface $em
     */
    public function index(
        $page,
        Request $request,
        MotionFilter $motionFilter,
        MotionRepository $motionRepository,
        Paginator $paginator,
        SessionInterface $session,
        PageManager $pageManager,
        ParameterManager $parameterManager
    ) {
        $motionFilter = $session->get('motionFilter') ?? $motionFilter;
        $motionRepository->setCurrentLocale($request->getLocale());
        $form = $this->createForm(MotionFilterType::class, $motionFilter);
        $form->handleRequest($request);
        if ($form->isSubmitted()) {
            $session->set('motionFilter', $motionFilter);
        }
        /** @var Pagerfanta $paginator */
        $paginator = $paginator->create(
            $motionRepository->getMotionsFormFilterQuery($motionFilter->getSelectedTags()),
            $page,
            Motion::PAGINATION_LIST_LIMIT
        );

        return $this->render(
            'motion/index.html.twig',
            [
                'motionFilter' => $motionFilter,
                'motions' => $paginator,
                'form' => $form->createView(),
                'page' => $pageManager->getOrCreatePage('database', 'Database'),
                'parameters' => $parameterManager->getParameters(),
            ]
        );
    }

    /**
     * @Route("motions/clean", name="motion_filter_resetting")
     * @Method({"GET"})
     *
     * @param SessionInterface $session
     *
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function resetSearch(SessionInterface $session)
    {
        $session->remove('motionFilter');
        $this->addFlash('success', 'flash.motion_filter.resetting');

        return $this->redirectToRoute('motion_index');
    }

    /**
     * @Route("motion/{id}", name="motion_show")
     * @Entity("motion", expr="repository.getMotionShow(id)")
     *
     * @param Motion $motion
     *
     * @return Response
     */
    public function show(Motion $motion)
    {
        return $this->render(
            'motion/show.html.twig',
            [
                'motion' => $motion,
            ]
        );
    }
}

templates/motion/_motions_filter.html.twig
{% form_theme form 'bootstrap_4_layout.html.twig' %}
<div class="motionsFilter plavimopWell">
    {{ form_start(form,{'action': path('motion_index')} ) }}

    {{ form_widget(form.selectedTags) }}
    <div class="text-right">
        <a href="{{ path('motion_filter_resetting') }}" class="btn btn-secondary">{{ 'action.reset'|trans }}</a>
        <input type="submit" value="{{ 'action.search'|trans }}" class="btn btn-info">
    </div>
    {{ form_end(form) }}
</div>

templates/motion/_motions_list.html.twig
<div class="motionsList">
    {% for motion in motions %}
        <div class="motionsList__item plavimopWell">
            <div class="row">
                <div class="col">
                    <div class="row no-gutters">
                        <div class=" col-lg-5">
                            <div class="d-flex flex-column justify-content-between" style="height: 100%;">
                                <p class="motionsList__itemTitle">{{ motion.title }}</p>
                                <div>
                                    <span class="motionsList__itemTitle">Tags : </span>
                                    {% for tag in motion.tags %}
                                        <span class="badge badge-{{ (tag.id in motionFilter.selectedTagsIds)? "secondary":"info" }}">
                                    <i class="fa fa-tag"></i> {{ tag.label }}</span>
                                    {% endfor %}
                                </div>
                                <p class="text-center">
                                    <a class="btn btn-light" href="{{ path('motion_show', {'id': motion.id}) }}"
                                       title="Details">{{ 'action.show_motion'|trans }}</a>
                                </p>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="acquisition__preview">
                                <div align="center" class="embed-responsive embed-responsive-4by3">
                                    <video data-preview-id="{{ motion.id }}" loop class="embed-responsive-item"
                                           controls controlsList="nodownload">
                                        <source src="{{ asset(vich_uploader_asset(motion.acquisitions.first, 'previewFile')) }}"
                                                type=video/mp4>
                                    </video>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <p class="motionsList__itemTitle">
                                {{ 'label.acquisition'|trans }}{{ (motion.acquisitions|length > 1)? "s":"" }}</p>
                            {% for acquisition in motion.acquisitions %}
                                <div>
                                    <span title="{{ acquisition.acqDate|date('Y-m-d') }}" data-toggle="tooltip">
                                        #{{ acquisition.id }} :
                                    </span>
                                    {% if is_granted('download',acquisition) %}
                                        <a class="btn"
                                           href="{{ path('acquisition_download', {'id': acquisition.id}) }}">.c3d</a>
                                    {% else %}
                                        <a class="btn disabled" href="#"
                                           title="{{ 'label.need_authentication'|trans }}">.c3d</a>
                                    {% endif %}
                                    {% if acquisition.previewFile is defined %}
                                        <a href="{{ asset(vich_uploader_asset(acquisition, 'previewFile')) }}"
                                           class=" btn js-change-preview" data-preview-id="{{ motion.id }}">.mp4</a>
                                    {% endif %}
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
</div>

templates/motion/index.html.twig
{% extends 'page/layout.html.twig' %}


{% block page_body %}
    {% if parameters.databasePdfManual %}
        <p class="float-right">
            <a href="{{ vich_uploader_asset(parameters,'databasePdfManualFile') }}" class="btn btn-lg btn-dark"
               download="PLAViMoP - Database manual.pdf">
                <i class="fa fa-book"></i> {{ 'action.download_database_manual'|trans }}
            </a>
        </p>
    {% endif %}
    {{ page.content|raw }}


    <div class="row">
        <div class="col-md-8 offset-md-4">
            <div class="d-flex">
                <p class="text-center align-self-center font-weight-bold mx-2">{{ (motionFilter.selectedTags|length == 0)?
                    "All results":"Motions filtered" }} :
                    {{ motions.currentPageOffsetStart }} to {{ motions.currentPageOffsetEnd }} out
                    of {{ motions.nbResults }}
                    {% for tag in motionFilter.selectedTags %}
                        <span class="badge badge-secondary">
                            <i class="fa fa-tag"></i> {{ tag.label }}
                        </span>
                    {% endfor %}
                </p>
                {% include 'motion/_motions_paginator.html.twg' %}
            </div>
        </div>
        <div class="col-md-4">
            {% include 'motion/_motions_filter.html.twig' %}
        </div>
        <div class="col">
            {% include 'motion/_motions_list.html.twig' %}
            {% include 'motion/_motions_paginator.html.twg' %}
        </div>
    </div>
{% endblock %}

{% block javascript %}
    {{ parent() }}
    <script src="{{ asset('build/js/motion.js') }}"></script>
{% endblock %}

templates/motion/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'label.motion_acquisitions'|trans }} :  {{ motion.title }} {% endblock %}
{% block description %}{{ 'label.motion_acquisitions'|trans }} -  {{ motion.title }} {% endblock %}
{% block body %}
    <nav aria-label="breadcrumb" role="navigation">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ path('homepage') }}">{{ 'title.homepage'|trans }}</a></li>
            <li class="breadcrumb-item"><a href="{{ path('motion_index') }}">{{ 'title.database'|trans }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ motion.title }}</li>
        </ol>
    </nav>
    <div class="motionShow">
        <h1 class="display-4 plavimopWell">{{ 'label.motion'|trans }} : {{ motion.title }}</h1>
        <div class="motionShow_tags plavimopWell">
            <h2>{{ 'label.associated_tags'|trans }} :</h2>
            <div class="row">
                {% for tag in motion.tags %}
                    <div class="col-6 col-sm-3 col-md">
                        {{ tag.type.label }}<br>
                        <span class="badge badge-secondary"><i class="fa fa-tag"></i> {{ tag.label }}</span>
                    </div>
                {% endfor %}
            </div>
        </div>

        <div class="motionShow_acquisitions">
            {% for acquisition in motion.acquisitions if acquisition.valid %}
            <div class="motionShow_acquisition plavimopWell">
                <div class="d-flex justify-content-between align-items-center">
                    <h2>{{ 'label.acquisition'|trans }} #{{ acquisition.id }}</h2>
                    {% if is_granted('download',acquisition) %}
                        <a href="{{ path('acquisition_download', {'id': acquisition.id}) }}"
                           class="btn btn-small btn-primary">{{ 'action.download_acquisition'|trans }}</a>
                    {% endif %}
                    <strong>{{ acquisition.user.institute }}</strong>
                </div>
                <div class="row">
                    {% if acquisition.previewFile is defined %}
                        <div class="col-12">
                            <hr>
                        </div>
                        <div class="col-md-4">
                            <div class="acquisition__preview">
                                <div align="center" class="embed-responsive embed-responsive-4by3">
                                    <video loop class="embed-responsive-item" controls controlsList="nodownload">
                                        <source src="{{ asset(vich_uploader_asset(acquisition, 'previewFile')) }}"
                                                type=video/mp4>
                                    </video>
                                </div>
                            </div>
                            <div class="my-2">
                                <h4>{{ 'label.process'|trans }}</h4>
                                {% include 'acquisition_process/_acquisition_process_show.html.twig'  with {acquisitionProcess: acquisition.acquisitionProcess} %}
                            </div>
                        </div>
                        <div class="col-md-8">
                            {% if acquisition.comment %}
                                <h3>{{ 'label.comment'|trans }}</h3>
                                <p>{{ acquisition.comment|nl2br }}</p>
                            {% endif %}
                            <h3>{{ 'label.recognitions'|trans }}</h3>
                            <div class="d-flex align-items-start justify-content-between">
                                <ul>
                                    <li>{{ 'label.number_of_inquiries'|trans }}
                                        : {{ acquisition.recognitions|length }}</li>
                                    <li>{{ 'label.recognition_rate'|trans }} : {{ acquisition.recognitionRate|round }}
                                        %
                                    </li>
                                </ul>
                                {% if acquisition.recognitions|length %}
                                    {% if is_granted('download',acquisition) %}
                                        <a class="btn btn-info" title="Download recognitions csv"
                                           href="{{ path('acquisition_export_recognitions', {'id': acquisition.id}) }}">
                                            {{ 'action.download_recognition_csv'|trans }}
                                        </a>
                                    {% endif %}
                                {% endif %}
                            </div>
                            <div class="row">
                                {% for typeLabel, typeData in  acquisition.recognitionsTags %}
                                    <div class="col-sm-4">
                                        <div class="motionShow__recognitionChart"
                                             data-plot-title="{{ typeLabel|json_encode|e('html_attr') }}"
                                             data-plot-data="{{ typeData|json_encode|e('html_attr') }}">
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
        {% else %}
            <div class="motionShow_acquisition plavimopWell">
                <h2>{{ 'paragraph.no_acquisition'|trans }}</h2>
            </div>
        {% endfor %}
    </div>
{% endblock %}
{% block javascript %}
    {{ parent() }}
    <script src="{{ asset('src/plotly/plotly.min.js') }}"></script>
    <script src="{{ asset('build/js/motionShow.js') }}"></script>
{% endblock %}